import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import HeaderTitle from "./components/HeaderTitle";
import SectionId from "./components/SectionId";
import Footer from "./components/Footer";
import CVEntry from "./components/CvEntry";
import SectionPost from "./components/SectionPost";
import Contacts from "./components/Contact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderTitle></HeaderTitle>
        <Navbar></Navbar>
        <SectionId></SectionId>
        <SectionPost></SectionPost>
         
          
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
